import type { FunFact, Word } from "./types";

/**
 * Demo-mode seed data. Mirrors supabase/seed.sql so the app works
 * fully offline before Supabase is connected.
 */
export const MOCK_WORDS: Word[] = [
  {
    id: "w1",
    english_word: "Nose",
    konkani_word: "Naak",
    pronunciation: 'naak (rhymes with "clock")',
    category: "body",
    difficulty: "beginner",
    mnemonic: '"Naak" sounds like "knock" — imagine a nose knocking on a door!',
    image_prompt: "A cute cartoon nose knocking on a wooden door",
    image_url: "https://placehold.co/600x400/ffb020/1e3a3a?text=Nose+%E2%86%92+Naak",
    example_sentence: "Mhaji naak lamb asa. (My nose is long.)",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "w2",
    english_word: "Water",
    konkani_word: "Udok",
    pronunciation: "oo-dohk",
    category: "nature",
    difficulty: "beginner",
    mnemonic: '"Udok" sounds like "you dock" — you dock your boat in the water!',
    image_prompt: "A happy boat docking in sparkling blue water",
    image_url: "https://placehold.co/600x400/06b6d4/ffffff?text=Water+%E2%86%92+Udok",
    example_sentence: "Mhaka udok zai. (I want water.)",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "w3",
    english_word: "Fish",
    konkani_word: "Nishtem",
    pronunciation: "nish-tem",
    category: "food",
    difficulty: "beginner",
    mnemonic: '"Nishtem" — a fish swimming through a NICE system of coral!',
    image_prompt: "A smiling cartoon fish swimming through a maze of colorful coral",
    image_url: "https://placehold.co/600x400/0891b2/ffffff?text=Fish+%E2%86%92+Nishtem",
    example_sentence: "Goenkar nishtem khatat. (Goans eat fish.)",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "w4",
    english_word: "House",
    konkani_word: "Ghor",
    pronunciation: 'gh-or (like "gore" with soft g)',
    category: "places",
    difficulty: "beginner",
    mnemonic: '"Ghor" sounds like "gore"-geous — a GORgeous house!',
    image_prompt: "A gorgeous little coastal cottage with a red tiled roof and palm trees",
    image_url: "https://placehold.co/600x400/ff6f61/ffffff?text=House+%E2%86%92+Ghor",
    example_sentence: "Mhojem ghor lhan asa. (My house is small.)",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "w5",
    english_word: "Sun",
    konkani_word: "Suryo",
    pronunciation: "soor-yoh",
    category: "nature",
    difficulty: "beginner",
    mnemonic: '"Suryo" — SIR YO! The sun greets you every morning like a cheerful friend.',
    image_prompt: "A smiling cartoon sun tipping its hat and saying yo",
    image_url: "https://placehold.co/600x400/f59e0b/1e3a3a?text=Sun+%E2%86%92+Suryo",
    example_sentence: "Suryo udelo. (The sun has risen.)",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "w6",
    english_word: "Mother",
    konkani_word: "Avoy",
    pronunciation: "ah-voy",
    category: "family",
    difficulty: "beginner",
    mnemonic: '"Avoy" — AHOY! Your mother waves ahoy from the kitchen.',
    image_prompt: "A warm cartoon mother waving ahoy like a friendly sailor",
    image_url: "https://placehold.co/600x400/16a34a/ffffff?text=Mother+%E2%86%92+Avoy",
    example_sentence: "Mhoji avoy randta. (My mother is cooking.)",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "w7",
    english_word: "Coconut",
    konkani_word: "Naral",
    pronunciation: "nah-rull",
    category: "food",
    difficulty: "beginner",
    mnemonic: `"Naral" — it's only NATURAL to find coconuts on the Konkan coast!`,
    image_prompt: "A cartoon coconut relaxing naturally on a beach chair under a palm tree",
    image_url: "https://placehold.co/600x400/15803d/ffffff?text=Coconut+%E2%86%92+Naral",
    example_sentence: "Naralachi kadi ruchik asa. (Coconut curry is tasty.)",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "w8",
    english_word: "Moon",
    konkani_word: "Chondrim",
    pronunciation: "chon-drim",
    category: "nature",
    difficulty: "intermediate",
    mnemonic: '"Chondrim" — the moon CHARMED him with its silver light.',
    image_prompt: "A dreamy cartoon moon casting a charming silver glow over the sea",
    image_url: "https://placehold.co/600x400/0e7490/ffffff?text=Moon+%E2%86%92+Chondrim",
    example_sentence: "Chondrim sundor dista. (The moon looks beautiful.)",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "w9",
    english_word: "Bird",
    konkani_word: "Sukonnem",
    pronunciation: "soo-kon-nem",
    category: "animals",
    difficulty: "intermediate",
    mnemonic: '"Sukonnem" — a bird singing SO CONtently on a branch.',
    image_prompt: "A colorful parrot singing contently on a coconut palm branch",
    image_url: "https://placehold.co/600x400/06b6d4/1e3a3a?text=Bird+%E2%86%92+Sukonnem",
    example_sentence: "Sukonnem gaita. (The bird is singing.)",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "w10",
    english_word: "Love",
    konkani_word: "Mog",
    pronunciation: 'mohg (rhymes with "vogue")',
    category: "feelings",
    difficulty: "beginner",
    mnemonic: '"Mog" — love is always in VOGUE, and it starts with a warm MuG of tea.',
    image_prompt: "Two cartoon mugs of chai leaning into a heart shape",
    image_url: "https://placehold.co/600x400/ff6f61/ffffff?text=Love+%E2%86%92+Mog",
    example_sentence: "Tujo mog kortam. (I love you.)",
    created_at: "2026-01-01T00:00:00Z",
  },
];

export const MOCK_FUN_FACTS: FunFact[] = [
  {
    id: "f1",
    fact_text:
      "Konkani is spoken by about 2.5 million people along India's beautiful western coast — Goa, Karnataka, Maharashtra, and Kerala!",
    unlock_points: 50,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "f2",
    fact_text:
      "Konkani is written in five different scripts: Devanagari, Roman, Kannada, Malayalam, and Perso-Arabic. Talk about flexible!",
    unlock_points: 100,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "f3",
    fact_text:
      "Konkani became the official language of Goa in 1987, after a passionate people's movement to protect it.",
    unlock_points: 150,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "f4",
    fact_text:
      'The word "Konkani" comes from "Konkan" — the lush coastal strip between the Sahyadri mountains and the Arabian Sea.',
    unlock_points: 200,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "f5",
    fact_text:
      'Konkani has borrowed words from Portuguese during 450 years of contact — like "janel" (window) from "janela"!',
    unlock_points: 250,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "f6",
    fact_text:
      "Konkani mando music blends Goan folk melodies with western harmonies — it's often sung at weddings!",
    unlock_points: 300,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "f7",
    fact_text:
      "Konkani was recognized in the 8th Schedule of the Indian Constitution in 1992, making it one of India's 22 official languages.",
    unlock_points: 350,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "f8",
    fact_text:
      "In Konkani, the same word can change meaning with tone and context — coastal conversations are full of playful wordplay.",
    unlock_points: 400,
    created_at: "2026-01-01T00:00:00Z",
  },
];
